export const OFFERING_TYPE = {
  "Align Offering": false,
  "Launch Offering": false,
  "Scale Offering": false,
  "Optimize Offering": false,
  "V1 Align Offering": false,
  "V1 Launch Offering": false,
  "V1 Scale Offering": false,
  "V1 Optimize Offering": false,
  "Foundation Launch": false,
  "DK": false,
  "DK Only": false,
  "SK": false,
  "SK Only": false,
  "TBD": false,
};

export const MATURITY_LEVEL = {
  "5": true,
  "4": true,
  "3": true,
  "2": true,
  "1": false,
  "0": false,
};

export const GSP_INDUSTRYVERTICALS = {
  "Advisory": false,
  "AI": false,
  "Amazon Connect": false,
  "Analytics Big Data": false,
  "CAF": false,
  "Database": false,
  "DevOps": false,
  "Elemental": false,
  "End User Compute": false,
  "HPC": false,
  "IoT": false,
  "Microsoft": false,
  "Migrations": false,
  "Operational Integration": false,
  "SAP": false,
  "SAS (Security Assurance Services)": false,
  "Security": false,

  "Automotive": false,
  "FinServ (Financial Services)": false,
  "Healthcare & Life Sciences": false,
  "Manufacturing": false,
  "Media & Entertainment": false,
  "Oil & Gas": false,
  "Retail": false,
  "Telecom": false,
};