export const OFFERING_TYPE = {
  "Align Offering": true,
  "Launch Offering": true,
  "Scale Offering": true,
  "Optimize Offering": true,
  "V1 Align Offering": true,
  "V1 Launch Offering": true,
  "V1 Scale Offering": true,
  "V1 Optimize Offering": true,
  "Foundation Launch": true,
  "DK": true,
  "DK Only": true,
  "SK": true,
  "SK Only": true,
  "TBD": true,
};

export const MATURITY_LEVEL = {
  "5": true,
  "4": true,
  "3": true,
  "2": true,
  "1": false,
  "0": false,
};

export const GSP_INDUSTRYVERTICALS = {
  "Advisory": true,
  "AI": true,
  "Amazon Connect": true,
  "Analytics Big Data": true,
  "CAF": true,
  "Database": true,
  "DevOps": true,
  "Elemental": true,
  "End User Compute": true,
  "HPC": true,
  "IoT": true,
  "Microsoft": true,
  "Migrations": true,
  "Operational Integration": true,
  "SAP": true,
  "SAS (Security Assurance Services)": true,
  "Security": true,

  "Automotive": true,
  "FinServ (Financial Services)": true,
  "Healthcare & Life Sciences": true,
  "Manufacturing": true,
  "Media & Entertainment": true,
  "Oil & Gas": true,
  "Retail": true,
  "Telecom": true,
};