// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8fda2220-c551-4e2d-9ad1-994efe14c892",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "70052dba6c3c42418c1be2aeec5875c7",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "proserveportfolio-host-bucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dpdegv5hknovo.cloudfront.net"
};


export default awsmobile;
